#!/usr/bin/env bash


. .envrc || exit 1

#psql "postgresql://${DB_USER}:${DB_PASSWD}@127.0.0.1:${PROXYSQL_DB_PORT}/${DB_NAME}" -v PROMPT1='%M:%> %n@%/ %R%# '
psql "postgresql://${PROXYSQL_DB_USER}:${PROXYSQL_DB_PASSWD}@127.0.0.1:${PROXYSQL_DB_PORT}/${DB_NAME}" -v PROMPT1='%M:%> %n@%/ %R%# '
